[package]
name = "qualium-tests-network"
version.workspace = true
edition = "2021"

[dependencies]
qualium-core = { path = "../../crates/qualium-core" }
qualium-network = { path = "../../crates/qualium-network" }
qualium-filter = { path = "../../crates/qualium-filter" }
tokio = { workspace = true }
