[package]
name = "qualium-vault"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
qualium-core = { path = "../qualium-core" }
qualium-crypto = { path = "../qualium-crypto" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }
uuid = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
